trainer:
  name: Trainer
  num_epochs: 100

dataset:
  name: Cat_Dog
  root: data
  batch_size: 32

model:
  name: MobileNet

optimizer:
  name: Adam
  lr: 1.e-2

scheduler:
  name: StepLR
  step_size: 10
